<?php
/**
 * @file
 * PayPalSdk module to manage PayPal integration
 */

require_once (__DIR__ . '/PayPal-PHP-SDK/vendor/autoload.php');

use PayPal\Api\Amount;
use PayPal\Api\Details;
use PayPal\Api\Item;
use PayPal\Api\ItemList;
use PayPal\Api\Payer;
use PayPal\Api\Payment;
use PayPal\Api\RedirectUrls;
use PayPal\Api\Transaction;
use PayPal\Api\PaymentExecution;

/**
 * Implements hook_menu().
 */
function paypalsdk_menu() {
    $items = [];
    $items['paypalsdk_test'] = [
        'title' => 'Paypal SDK Test',
        'page callback' => '_paypalsdk_test',
        'access arguments' => ['administer content types'],
    ];
    return $items;
}

function _paypalsdk_test() {
    drupal_set_message('Testing it');

    $apiContext = new \PayPal\Rest\ApiContext(
        new \PayPal\Auth\OAuthTokenCredential(
            'AY3gQQj4-3Xd51rQKr5l0BpgtPRQptmmNosR-q-XQysWzDy2m1cwvs174MU3zNOA2T2ej4g8MAndGMDy',     // ClientID
            'EPFMFlnWhvhErfbHqRIOyWAti7ZSqPCVGAgk7zjK0ojEVyn5qyDtexIqVZmGkdMx6a8nDChsEj9FNz_X'      // ClientSecret
        )
    );

    $payer = new \PayPal\Api\Payer();
    $payer->setPaymentMethod('paypal');

    $amount = new \PayPal\Api\Amount();
    $amount->setTotal('100.00');
    $amount->setCurrency('USD');

    $transaction = new \PayPal\Api\Transaction();
    $transaction->setAmount($amount);

    $baseUrl = "http://" . $_SERVER['SERVER_NAME'] . $_SERVER['REQUEST_URI'];

    $redirectUrls = new \PayPal\Api\RedirectUrls();
    $redirectUrls->setReturnUrl($baseUrl)->setCancelUrl($baseUrl."/index.php");

    $payment = new \PayPal\Api\Payment();
    $payment->setIntent('sale')
        ->setPayer($payer)
        ->setTransactions(array($transaction))
        ->setRedirectUrls($redirectUrls);

    $payment = new Payment();
    $payment->setIntent("authorize")
        ->setPayer($payer)
        ->setRedirectUrls($redirectUrls)
        ->setTransactions(array($transaction));

    try {

        $payment->create($apiContext);
        $approvalUrl = $payment->getApprovalLink();
        if($approvalUrl){
           /// header("Location : " .  $approvalUrl);
        }

        drupal_set_message('<pre>' . print_r($payment, 1) . '</pre>');

    }
    catch (Exception $ex) {
        drupal_set_message('<pre>' . print_r($ex, 1) . '</pre>');
        exit(1);
    }


    if(isset($_GET['paymentId']) && isset($_GET['PayerID']) ){

        $payment = Payment::get($_GET['paymentId'], $apiContext);
        $execution = new PaymentExecution();
        $execution->setPayerId($_GET['PayerID']);
        try{
            $result = $payment->execute($execution, $apiContext);
            drupal_set_message('Payment Done - <pre>' . print_r($result, 1) . '</pre>');
        }
        catch(Exception $e){
            drupal_set_message('<pre>' . print_r($e, 1) . '</pre>');
        }
    }

    return '123';
}